# Generated by Django 2.2.8 on 2020-03-24 06:16

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200324_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(default='', verbose_name='文章内容'),
        ),
    ]
