# Generated by Django 2.2.8 on 2020-03-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200324_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, default='此文章没有摘要', null=True, verbose_name='文章摘要'),
        ),
    ]
