# Generated by Django 2.2.8 on 2020-03-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0002_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='clicknum',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
