# Generated by Django 2.2.8 on 2020-03-26 05:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0003_question_clicknum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='问题内容'),
        ),
    ]
